### ISSUE TITLE
Couple thoughts on ideas for improvement

### ISSUE THREAD

**Issue by bsavery** [jlampel/extra_lights#14]
So your addon adds some good presets for lights. 
1.  Would it make sense to have the presets in the add light menu include the Wattage or W equivalent.  That is instead of:
1000 lm incandescent ... -> 1000 lm (65 W) incandescent.  
And of course with equivalent for the different efficacy of LED.

Obviously Lumen is more precise but the average user probably would like the W hint.

2.  Add the lights with nodes rather than using conversion of presets to settings when adding, I think it would be good to be able to tweak values after.  It looks like from the code that presets are added by "baking" the values into the emission color and power, I think leaving them so people can tweak would be better.

**Comment by jlampel** [comment]
Thanks Brian! I agree about the naming. There is a Use Nodes checkbox in the Redo Panel when adding a light, but it's not on by default since nodes won't work with Eevee. I plan on making it a preference in the future. I've written down both on separate issues and will track them there.
