### ISSUE TITLE
No K values in the light properties interface in Blender 2.83

### ISSUE THREAD

**Issue by AssafNegev** [jlampel/extra_lights#21]
The option to use K values is missing in Blender 2.83.
![Annotation 2020-06-26 103600](https://user-images.githubusercontent.com/38858000/85832572-07fb2400-b799-11ea-9365-92da48bb6867.png)

![Annotation 2020-06-26 103642](https://user-images.githubusercontent.com/38858000/85832593-0d586e80-b799-11ea-86fc-70abe8c46ce0.png)

**Comment by jlampel** [comment]
Hi, thanks for reporting issues! This one is not one I can tackle though - the physical lights panel is from the Photographer addon and not Extra Lights. Please double check that you have that one enabled in 2.83.

**Comment by AssafNegev** [comment]
I have that enabled, didn't notice it was an older version of Photographer.
Thanks :)
