### ISSUE TITLE
Missing connection

### ISSUE THREAD

**Issue by MarjBerry** [jlampel/extra_lights#22]
Click on Emergency Light 70 lm Mini T5 (Incandescent) IES opens instead Floodlight 890 lm MR16 (Incandescent) IES

**Comment by jlampel** [comment]
Hi, thank you for letting me know! I'm not sure how this is possible since it grabs the IES text based on the name of the light. I haven't been able to replicate this issue. Are you using the [latest version ](https://github.com/jlampel/extra_lights/releases/tag/v1.0), and does this happen to you even in a blank file?

**Comment by MarjBerry** [comment]
Well...I tried a blank file. No-go on that light. 
I removed the add-on, tried the file from Blender Market. But that list has hardly any lights in comparison, and I didn’t spot that light in the list, so I removed the add-on.
I deleted from my computer everything related to the add-on, then
I went back to CGC lighting course, and from there, added the add-on again. Used a new file. No go.

I have tried every light and documented the with- and without-nodes settings for each light (for myself...because I will never remember it all). Some of them I had never heard of and the amount of work that must have gone into creating them amazed me. The number and variety of the lights are so fun I forgot to study the lighting course for a day or so.
I can’t answer to the programming or why that light won’t appear for me. I thought at first that I broke something while poking around, but total removal and reinstallation didn’t fix. But I won’t miss it. I suspect it might bother you, but if the rest of the world has that particular light...then the problem is at this end and I am happy enough. 😊
M

**Comment by jlampel** [comment]
Oh, I see, you got it from CG Cookie! It looks like I forgot to update that one when I made a couple fixes for the BM a while ago. Please try downloading it again: https://cgcookie.com/resource/extra-lights

Also, just to clarify - the Blender Market version has the same amount of lights as the CGC one. It's the free GitHub version that has fewer. 

Happy lighting!

**Comment by MarjBerry** [comment]
All right! Thank you so much and for the great course too.
M
