### ISSUE TITLE
Is this compatible with Blender 2.93?

### ISSUE THREAD

**Issue by DreDesigns** [jlampel/extra_lights#25]
I'm following instructions and it does not seem to pop up after I install... am i doing it right? It doesn't install the whole folder and i tried installing all the items in folder separately, but nothing shows up in the addons.

**Comment by jlampel** [comment]
Hi there, it sure does! I just tested installing it again. Please be sure to install the .zip file directly and not the unzipped folder, similar to other Blender addons. If you're on a Mac your browser may automatically unzip when you download, and if that's the case please re-zip before installing via the user preferences.
