### ISSUE TITLE
cannot install on Blender 3.4

### ISSUE THREAD

**Issue by hypericon** [jlampel/extra_lights#28]
hello folks,

I was trying to install it on 3.4 but, even I am not receving any error messages, the addon is not displayed in the installed list and cannot see anywhere...
is it working on blender 3.4+?

ty

**Comment by jlampel** [comment]
Hi, the addon still works the same in 3.4. It sounds like the wrong folder or file is being selected. Please try downloading the latest release version](https://github.com/jlampel/extra_lights/releases/tag/v1-1) and installing the .zip using Blender's preferences. Unzipping, selecting a file within the folder, or installing manually via the file explorer can result in the issue you've described, so I'm guessing that's the cause.

**Comment by hypericon** [comment]
I usually do this way... :)
which is the only way to install the addons :)

in any cases, re-downloading did his job!

**Comment by jlampel** [comment]
Oh perfect, glad that worked!
